### ISSUE TITLE
BubbleTree Reboot

### ISSUE THREAD

**Issue by pwalsh** [okfn/bubbletree#36]
# Description

Hi, 2015 calling. It is time to reboot and dress up the BubbleTree.

We just did a first pass refactor so we can [`npm install`](https://github.com/okfn/bubbletree/pull/35) and get it into a React app. Lot's more that can be done!

**We at OK will do work on this over the coming months, but if anyone out there watching this repo wants to chip in and bring BubbleTree forward, please let us know here.**

# Tasks

* [ ] Style! Yes, we like to write neat and consistent JS these days :). Even using the conservative google style guide via jscs `npm run review` pretty much every line of code here throws a warning
* [ ] Write in ES6, compile for dist
* [ ] Port to D3 (Is this worth it?)
* [ ] Ship components for Angular and React (we already have one for React, but need to break it out into a new repo)

**Comment by pudo** [comment]
:+1: this would be so cool to have. I have no idea how much work the d3 port would be, but it'd feel soo good :)

**Comment by pwalsh** [comment]
@pudo https://github.com/okfn/bubbletree/issues/32#issuecomment-164748521

**Comment by M-Danes** [comment]
@pwalsh I read your call with great interest. I am wondering, whats the status and are you still eager to team-up? Looking forward to hear from you!

**Comment by pwalsh** [comment]
Hi @M-Danes 

Well, we did various fixes here, but not a total reboot. We'd be super interested in someone taking this up.

**Comment by M-Danes** [comment]
Hi @pwalsh,

Thanks for the quick response! Do I get it right that you are searching for someone to take the lead?

I need some time to explore the code and see which parts of your 'wish-list' I can cover in my side-project. I will come back to you in some days.
